/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rup.lab;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Mahe
 */
public class createtable extends javax.swing.JFrame {

    /**
     * Creates new form createtable
     */
    String[] day={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};
    String[] hour={"FIRST","SECOND","THIRD","FOURTH","FIFTH","SIXTH","SEVENTH","EIGHTH"};
    String branch,dept;
    int semt,sec;
    public createtable(String a,String b,int n,int m){
        initComponents();
        branch=b;
        dept=a;
        semt=n;
        sec=m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jButton1.setText("CREATE TABLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int k=0;
            if(semt!=0){
                k=3;
            }
            if(semt==0){
                k=4;
            }
        for(int i=k;i<8;i=i+2){
                for(int j=1;j<=sec;j++){
                    char ch=(char)(j+64);
                       System.out.println(i+" "+ch);
                       create(i,ch);
                }
       }
        jOptionPane1.showMessageDialog(null, "Table has been created", "Success", jOptionPane1.INFORMATION_MESSAGE);
        this.setVisible(false);
        new admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void create(int sem,char sec){
        try{
        Connection con = (Connection)DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL","system", "qwerty123");
        Statement stmt=(Statement) con.createStatement();
        String query="select ID,Credits,TID from subject natural join teaches where section='"+sec+"' and ID like '"+(dept+sem)+"%'";
        ResultSet rs=stmt.executeQuery(query);
        String arr[][]=new String[10][3];
        
        int k=0,tc=0;
            while(rs.next()){
                arr[k][0]=rs.getString(1);
                arr[k][1]=rs.getString(2);
                arr[k][2]=rs.getString(3);
                k++;
            }
            if( sem==7){
                for(int i=0;i<k/2;i++){
                    String temp1=arr[i][0];
                    String temp2=arr[i][1];
                    String temp3=arr[i][2];
                    arr[i][0]=arr[k-i-1][0];
                    arr[i][1]=arr[k-i-1][1];
                    arr[i][2]=arr[k-i-1][2];
                    arr[k-i-1][0]=temp1;
                    arr[k-i-1][1]=temp2;
                    arr[k-i-1][2]=temp3;
                }
            }
        for(int i=0;i<k;i++){
            System.out.println(arr[i][0]+" "+arr[i][1]+" "+arr[i][2]);
            tc+=Integer.parseInt(arr[i][1]);
        }
        int x=0;
        int m=0;
        int n=0;
        if(sem==3||sem==4) n=0;
        if(sem==5||sem==6) n=4;
        if(sem==7) {n=0;m=5;}
        for(int i=0;i<tc;){
            if(Integer.parseInt(arr[x][1])!=0){
                    String SQL1="Select "+hour[n]+" from "+arr[x][2]+" where day='"+day[m]+"'";
                    System.out.println(SQL1);
                    ResultSet rss2=stmt.executeQuery(SQL1);
                    rss2.next();
                    String fl=rss2.getString(1);
                    System.out.println(fl);
                    if("0".equals(fl)){
                    String SQL="Update "+branch+"_"+sec+"_"+sem+" set "+hour[n]+"='" +arr[x][0]+"' where day='"+day[m]+"'";
                    System.out.println(SQL);
                    ResultSet rs1=stmt.executeQuery(SQL);
                    String SQL2="Update "+arr[x][2]+" set "+hour[n]+"='" +arr[x][0]+"' where day='"+day[m]+"'";
                    ResultSet rs2=stmt.executeQuery(SQL2);
                    i++;
                    n++;
                    arr[x][1]=Integer.toString((Integer.parseInt(arr[x][1])-1));
                    }
                    else{
                        x++;
                        continue;
                    }
                }
            if(n==8) {
                n=0;
                if (sem==7){
                    m--;
                }
                else m++;
            }
            if(n==4){
                if (sem==7){
                    m--;
                }
                else m++;
            }
            x++;
            if(x==k){
                x=0;
            }
        }
        
         for(int i=0;i<k;i++){
            System.out.println(arr[i][0]+" "+arr[i][1]+" "+arr[i][2]);
            tc+=Integer.parseInt(arr[i][1]);
        }
        
        }
        catch (SQLException e) {
            System.out.println("Connection Failed! Check output "+e);
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createtable("ICT","CCE",0,2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
